name: appwrite_function
description: Dart starter for Appwrite function.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  dart_appwrite: ^6.0.0
  fpdart: ^0.2.0
  freezed_annotation: ^2.1.0
      
dev_dependencies:
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  lint: ^1.10.0
  json_serializable:
  test: ^1.21.4
  mockito: ^5.3.0
