name: game_management_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  appwrite: ^6.0.0
  flutter:
    sdk: flutter
  fpdart: ^0.2.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  logger: ^1.1.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mockito: ^5.3.0
  very_good_analysis: ^3.0.1