name: marmot_playground
description: An app to play (1 at the moment) games with randos
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  adaptive_theme: ^3.1.1
  appwrite_ruq_api:
    path: packages/appwrite_ruq_api
  bloc: ^8.1.0
  cached_network_image: ^3.2.1
  collection: ^1.16.0
  envied: ^0.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_form_builder: ^7.5.0
  flutter_localizations:
    sdk: flutter
  fpdart: ^0.2.0
  freezed_annotation: ^2.1.0
  game_management_repository:
    path: packages/game_management_repository
  google_fonts: ^3.0.1
  intl: ^0.17.0
  json_annotation: ^4.6.0
  latlong2: ^0.8.1
  logger: ^1.1.0
  progress_state_button: ^1.0.4

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  envied_generator: ^0.2.2
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mockito: ^5.3.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - google_fonts/
