name: marmot_playground
description: An app to play (1 at the moment) games with randos
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  bloc: ^8.1.0
  cached_network_image: ^3.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_form_builder: ^7.5.0
  flutter_localizations:
    sdk: flutter
  fpdart: ^0.2.0
  freezed_annotation: ^2.1.0
  intl: ^0.17.0
  latlong2: ^0.8.1

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
