// Mocks generated by Mockito 5.3.0 from annotations
// in appwrite_function/test/function_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dart_appwrite/dart_appwrite.dart' as _i4;
import 'package:dart_appwrite/models.dart' as _i3;
import 'package:dart_appwrite/src/client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeDatabaseList_1 extends _i1.SmartFake implements _i3.DatabaseList {
  _FakeDatabaseList_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeDatabase_2 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeCollection_3 extends _i1.SmartFake implements _i3.Collection {
  _FakeCollection_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeCollectionList_4 extends _i1.SmartFake
    implements _i3.CollectionList {
  _FakeCollectionList_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeAttributeList_5 extends _i1.SmartFake implements _i3.AttributeList {
  _FakeAttributeList_5(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeAttributeBoolean_6 extends _i1.SmartFake
    implements _i3.AttributeBoolean {
  _FakeAttributeBoolean_6(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeAttributeEmail_7 extends _i1.SmartFake
    implements _i3.AttributeEmail {
  _FakeAttributeEmail_7(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeAttributeEnum_8 extends _i1.SmartFake implements _i3.AttributeEnum {
  _FakeAttributeEnum_8(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeAttributeFloat_9 extends _i1.SmartFake
    implements _i3.AttributeFloat {
  _FakeAttributeFloat_9(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeAttributeInteger_10 extends _i1.SmartFake
    implements _i3.AttributeInteger {
  _FakeAttributeInteger_10(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeAttributeIp_11 extends _i1.SmartFake implements _i3.AttributeIp {
  _FakeAttributeIp_11(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeAttributeString_12 extends _i1.SmartFake
    implements _i3.AttributeString {
  _FakeAttributeString_12(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeAttributeUrl_13 extends _i1.SmartFake implements _i3.AttributeUrl {
  _FakeAttributeUrl_13(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeDocumentList_14 extends _i1.SmartFake implements _i3.DocumentList {
  _FakeDocumentList_14(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeDocument_15 extends _i1.SmartFake implements _i3.Document {
  _FakeDocument_15(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeIndexList_16 extends _i1.SmartFake implements _i3.IndexList {
  _FakeIndexList_16(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeIndex_17 extends _i1.SmartFake implements _i3.Index {
  _FakeIndex_17(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [Databases].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabases extends _i1.Mock implements _i4.Databases {
  MockDatabases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get databaseId =>
      (super.noSuchMethod(Invocation.getter(#databaseId), returnValue: '')
          as String);
  @override
  set databaseId(String? _databaseId) =>
      super.noSuchMethod(Invocation.setter(#databaseId, _databaseId),
          returnValueForMissingStub: null);
  @override
  _i2.Client get client => (super.noSuchMethod(Invocation.getter(#client),
          returnValue: _FakeClient_0(this, Invocation.getter(#client)))
      as _i2.Client);
  @override
  _i5.Future<_i3.DatabaseList> list(
          {String? search,
          int? limit,
          int? offset,
          String? cursor,
          String? cursorDirection,
          String? orderType}) =>
      (super.noSuchMethod(
          Invocation.method(#list, [], {
            #search: search,
            #limit: limit,
            #offset: offset,
            #cursor: cursor,
            #cursorDirection: cursorDirection,
            #orderType: orderType
          }),
          returnValue: _i5.Future<_i3.DatabaseList>.value(_FakeDatabaseList_1(
              this,
              Invocation.method(#list, [], {
                #search: search,
                #limit: limit,
                #offset: offset,
                #cursor: cursor,
                #cursorDirection: cursorDirection,
                #orderType: orderType
              })))) as _i5.Future<_i3.DatabaseList>);
  @override
  _i5.Future<_i3.Database> create({String? name}) =>
      (super.noSuchMethod(Invocation.method(#create, [], {#name: name}),
              returnValue: _i5.Future<_i3.Database>.value(_FakeDatabase_2(
                  this, Invocation.method(#create, [], {#name: name}))))
          as _i5.Future<_i3.Database>);
  @override
  _i5.Future<_i3.Collection> get() =>
      (super.noSuchMethod(Invocation.method(#get, []),
              returnValue: _i5.Future<_i3.Collection>.value(
                  _FakeCollection_3(this, Invocation.method(#get, []))))
          as _i5.Future<_i3.Collection>);
  @override
  _i5.Future<_i3.Collection> update({String? name}) =>
      (super.noSuchMethod(Invocation.method(#update, [], {#name: name}),
              returnValue: _i5.Future<_i3.Collection>.value(_FakeCollection_3(
                  this, Invocation.method(#update, [], {#name: name}))))
          as _i5.Future<_i3.Collection>);
  @override
  _i5.Future<dynamic> delete() =>
      (super.noSuchMethod(Invocation.method(#delete, []),
          returnValue: _i5.Future<dynamic>.value()) as _i5.Future<dynamic>);
  @override
  _i5.Future<_i3.CollectionList> listCollections(
          {String? search,
          int? limit,
          int? offset,
          String? cursor,
          String? cursorDirection,
          String? orderType}) =>
      (super.noSuchMethod(
          Invocation.method(#listCollections, [], {
            #search: search,
            #limit: limit,
            #offset: offset,
            #cursor: cursor,
            #cursorDirection: cursorDirection,
            #orderType: orderType
          }),
          returnValue:
              _i5.Future<_i3.CollectionList>.value(_FakeCollectionList_4(
                  this,
                  Invocation.method(#listCollections, [], {
                    #search: search,
                    #limit: limit,
                    #offset: offset,
                    #cursor: cursor,
                    #cursorDirection: cursorDirection,
                    #orderType: orderType
                  })))) as _i5.Future<_i3.CollectionList>);
  @override
  _i5.Future<_i3.Collection> createCollection(
          {String? collectionId,
          String? name,
          String? permission,
          List<dynamic>? read,
          List<dynamic>? write}) =>
      (super.noSuchMethod(
          Invocation.method(#createCollection, [], {
            #collectionId: collectionId,
            #name: name,
            #permission: permission,
            #read: read,
            #write: write
          }),
          returnValue: _i5.Future<_i3.Collection>.value(_FakeCollection_3(
              this,
              Invocation.method(#createCollection, [], {
                #collectionId: collectionId,
                #name: name,
                #permission: permission,
                #read: read,
                #write: write
              })))) as _i5.Future<_i3.Collection>);
  @override
  _i5.Future<_i3.Collection> getCollection({String? collectionId}) =>
      (super.noSuchMethod(
          Invocation.method(#getCollection, [], {#collectionId: collectionId}),
          returnValue: _i5.Future<_i3.Collection>.value(_FakeCollection_3(
              this,
              Invocation.method(
                  #getCollection, [], {#collectionId: collectionId})))) as _i5
          .Future<_i3.Collection>);
  @override
  _i5.Future<_i3.Collection> updateCollection(
          {String? collectionId,
          String? name,
          String? permission,
          List<dynamic>? read,
          List<dynamic>? write,
          bool? enabled}) =>
      (super.noSuchMethod(
          Invocation.method(#updateCollection, [], {
            #collectionId: collectionId,
            #name: name,
            #permission: permission,
            #read: read,
            #write: write,
            #enabled: enabled
          }),
          returnValue: _i5.Future<_i3.Collection>.value(_FakeCollection_3(
              this,
              Invocation.method(#updateCollection, [], {
                #collectionId: collectionId,
                #name: name,
                #permission: permission,
                #read: read,
                #write: write,
                #enabled: enabled
              })))) as _i5.Future<_i3.Collection>);
  @override
  _i5.Future<dynamic> deleteCollection({String? collectionId}) =>
      (super.noSuchMethod(
          Invocation.method(
              #deleteCollection, [], {#collectionId: collectionId}),
          returnValue: _i5.Future<dynamic>.value()) as _i5.Future<dynamic>);
  @override
  _i5.Future<_i3.AttributeList> listAttributes({String? collectionId}) =>
      (super.noSuchMethod(
          Invocation.method(#listAttributes, [], {#collectionId: collectionId}),
          returnValue: _i5.Future<_i3.AttributeList>.value(_FakeAttributeList_5(
              this,
              Invocation.method(
                  #listAttributes, [], {#collectionId: collectionId})))) as _i5
          .Future<_i3.AttributeList>);
  @override
  _i5.Future<_i3.AttributeBoolean> createBooleanAttribute(
          {String? collectionId,
          String? key,
          bool? xrequired,
          bool? xdefault,
          bool? array}) =>
      (super.noSuchMethod(
          Invocation.method(#createBooleanAttribute, [], {
            #collectionId: collectionId,
            #key: key,
            #xrequired: xrequired,
            #xdefault: xdefault,
            #array: array
          }),
          returnValue:
              _i5.Future<_i3.AttributeBoolean>.value(_FakeAttributeBoolean_6(
                  this,
                  Invocation.method(#createBooleanAttribute, [], {
                    #collectionId: collectionId,
                    #key: key,
                    #xrequired: xrequired,
                    #xdefault: xdefault,
                    #array: array
                  })))) as _i5.Future<_i3.AttributeBoolean>);
  @override
  _i5.Future<_i3.AttributeEmail> createEmailAttribute(
          {String? collectionId,
          String? key,
          bool? xrequired,
          String? xdefault,
          bool? array}) =>
      (super.noSuchMethod(
          Invocation.method(#createEmailAttribute, [], {
            #collectionId: collectionId,
            #key: key,
            #xrequired: xrequired,
            #xdefault: xdefault,
            #array: array
          }),
          returnValue:
              _i5.Future<_i3.AttributeEmail>.value(_FakeAttributeEmail_7(
                  this,
                  Invocation.method(#createEmailAttribute, [], {
                    #collectionId: collectionId,
                    #key: key,
                    #xrequired: xrequired,
                    #xdefault: xdefault,
                    #array: array
                  })))) as _i5.Future<_i3.AttributeEmail>);
  @override
  _i5.Future<_i3.AttributeEnum> createEnumAttribute(
          {String? collectionId,
          String? key,
          List<dynamic>? elements,
          bool? xrequired,
          String? xdefault,
          bool? array}) =>
      (super.noSuchMethod(
          Invocation.method(#createEnumAttribute, [], {
            #collectionId: collectionId,
            #key: key,
            #elements: elements,
            #xrequired: xrequired,
            #xdefault: xdefault,
            #array: array
          }),
          returnValue: _i5.Future<_i3.AttributeEnum>.value(_FakeAttributeEnum_8(
              this,
              Invocation.method(#createEnumAttribute, [], {
                #collectionId: collectionId,
                #key: key,
                #elements: elements,
                #xrequired: xrequired,
                #xdefault: xdefault,
                #array: array
              })))) as _i5.Future<_i3.AttributeEnum>);
  @override
  _i5.Future<_i3.AttributeFloat> createFloatAttribute(
          {String? collectionId,
          String? key,
          bool? xrequired,
          double? min,
          double? max,
          double? xdefault,
          bool? array}) =>
      (super.noSuchMethod(
          Invocation.method(#createFloatAttribute, [], {
            #collectionId: collectionId,
            #key: key,
            #xrequired: xrequired,
            #min: min,
            #max: max,
            #xdefault: xdefault,
            #array: array
          }),
          returnValue:
              _i5.Future<_i3.AttributeFloat>.value(_FakeAttributeFloat_9(
                  this,
                  Invocation.method(#createFloatAttribute, [], {
                    #collectionId: collectionId,
                    #key: key,
                    #xrequired: xrequired,
                    #min: min,
                    #max: max,
                    #xdefault: xdefault,
                    #array: array
                  })))) as _i5.Future<_i3.AttributeFloat>);
  @override
  _i5.Future<_i3.AttributeInteger> createIntegerAttribute(
          {String? collectionId,
          String? key,
          bool? xrequired,
          int? min,
          int? max,
          int? xdefault,
          bool? array}) =>
      (super.noSuchMethod(
          Invocation.method(#createIntegerAttribute, [], {
            #collectionId: collectionId,
            #key: key,
            #xrequired: xrequired,
            #min: min,
            #max: max,
            #xdefault: xdefault,
            #array: array
          }),
          returnValue:
              _i5.Future<_i3.AttributeInteger>.value(_FakeAttributeInteger_10(
                  this,
                  Invocation.method(#createIntegerAttribute, [], {
                    #collectionId: collectionId,
                    #key: key,
                    #xrequired: xrequired,
                    #min: min,
                    #max: max,
                    #xdefault: xdefault,
                    #array: array
                  })))) as _i5.Future<_i3.AttributeInteger>);
  @override
  _i5.Future<_i3.AttributeIp> createIpAttribute(
          {String? collectionId,
          String? key,
          bool? xrequired,
          String? xdefault,
          bool? array}) =>
      (super.noSuchMethod(
          Invocation.method(#createIpAttribute, [], {
            #collectionId: collectionId,
            #key: key,
            #xrequired: xrequired,
            #xdefault: xdefault,
            #array: array
          }),
          returnValue: _i5.Future<_i3.AttributeIp>.value(_FakeAttributeIp_11(
              this,
              Invocation.method(#createIpAttribute, [], {
                #collectionId: collectionId,
                #key: key,
                #xrequired: xrequired,
                #xdefault: xdefault,
                #array: array
              })))) as _i5.Future<_i3.AttributeIp>);
  @override
  _i5.Future<_i3.AttributeString> createStringAttribute(
          {String? collectionId,
          String? key,
          int? size,
          bool? xrequired,
          String? xdefault,
          bool? array}) =>
      (super.noSuchMethod(
          Invocation.method(#createStringAttribute, [], {
            #collectionId: collectionId,
            #key: key,
            #size: size,
            #xrequired: xrequired,
            #xdefault: xdefault,
            #array: array
          }),
          returnValue:
              _i5.Future<_i3.AttributeString>.value(_FakeAttributeString_12(
                  this,
                  Invocation.method(#createStringAttribute, [], {
                    #collectionId: collectionId,
                    #key: key,
                    #size: size,
                    #xrequired: xrequired,
                    #xdefault: xdefault,
                    #array: array
                  })))) as _i5.Future<_i3.AttributeString>);
  @override
  _i5.Future<_i3.AttributeUrl> createUrlAttribute(
          {String? collectionId,
          String? key,
          bool? xrequired,
          String? xdefault,
          bool? array}) =>
      (super.noSuchMethod(
          Invocation.method(#createUrlAttribute, [], {
            #collectionId: collectionId,
            #key: key,
            #xrequired: xrequired,
            #xdefault: xdefault,
            #array: array
          }),
          returnValue: _i5.Future<_i3.AttributeUrl>.value(_FakeAttributeUrl_13(
              this,
              Invocation.method(#createUrlAttribute, [], {
                #collectionId: collectionId,
                #key: key,
                #xrequired: xrequired,
                #xdefault: xdefault,
                #array: array
              })))) as _i5.Future<_i3.AttributeUrl>);
  @override
  _i5.Future<dynamic> getAttribute({String? collectionId, String? key}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getAttribute, [], {#collectionId: collectionId, #key: key}),
          returnValue: _i5.Future<dynamic>.value()) as _i5.Future<dynamic>);
  @override
  _i5.Future<dynamic> deleteAttribute({String? collectionId, String? key}) =>
      (super.noSuchMethod(
          Invocation.method(
              #deleteAttribute, [], {#collectionId: collectionId, #key: key}),
          returnValue: _i5.Future<dynamic>.value()) as _i5.Future<dynamic>);
  @override
  _i5.Future<_i3.DocumentList> listDocuments(
          {String? collectionId,
          List<dynamic>? queries,
          int? limit,
          int? offset,
          String? cursor,
          String? cursorDirection,
          List<dynamic>? orderAttributes,
          List<dynamic>? orderTypes}) =>
      (super.noSuchMethod(
          Invocation.method(#listDocuments, [], {
            #collectionId: collectionId,
            #queries: queries,
            #limit: limit,
            #offset: offset,
            #cursor: cursor,
            #cursorDirection: cursorDirection,
            #orderAttributes: orderAttributes,
            #orderTypes: orderTypes
          }),
          returnValue: _i5.Future<_i3.DocumentList>.value(_FakeDocumentList_14(
              this,
              Invocation.method(#listDocuments, [], {
                #collectionId: collectionId,
                #queries: queries,
                #limit: limit,
                #offset: offset,
                #cursor: cursor,
                #cursorDirection: cursorDirection,
                #orderAttributes: orderAttributes,
                #orderTypes: orderTypes
              })))) as _i5.Future<_i3.DocumentList>);
  @override
  _i5.Future<_i3.Document> createDocument(
          {String? collectionId,
          String? documentId,
          Map<dynamic, dynamic>? data,
          List<dynamic>? read,
          List<dynamic>? write}) =>
      (super.noSuchMethod(
          Invocation.method(#createDocument, [], {
            #collectionId: collectionId,
            #documentId: documentId,
            #data: data,
            #read: read,
            #write: write
          }),
          returnValue: _i5.Future<_i3.Document>.value(_FakeDocument_15(
              this,
              Invocation.method(#createDocument, [], {
                #collectionId: collectionId,
                #documentId: documentId,
                #data: data,
                #read: read,
                #write: write
              })))) as _i5.Future<_i3.Document>);
  @override
  _i5.Future<_i3.Document> getDocument(
          {String? collectionId, String? documentId}) =>
      (super
          .noSuchMethod(Invocation.method(#getDocument, [], {#collectionId: collectionId, #documentId: documentId}),
              returnValue: _i5.Future<_i3.Document>.value(_FakeDocument_15(
                  this,
                  Invocation.method(#getDocument, [], {
                    #collectionId: collectionId,
                    #documentId: documentId
                  })))) as _i5.Future<_i3.Document>);
  @override
  _i5.Future<_i3.Document> updateDocument(
          {String? collectionId,
          String? documentId,
          Map<dynamic, dynamic>? data,
          List<dynamic>? read,
          List<dynamic>? write}) =>
      (super.noSuchMethod(
          Invocation.method(#updateDocument, [], {
            #collectionId: collectionId,
            #documentId: documentId,
            #data: data,
            #read: read,
            #write: write
          }),
          returnValue: _i5.Future<_i3.Document>.value(_FakeDocument_15(
              this,
              Invocation.method(#updateDocument, [], {
                #collectionId: collectionId,
                #documentId: documentId,
                #data: data,
                #read: read,
                #write: write
              })))) as _i5.Future<_i3.Document>);
  @override
  _i5.Future<dynamic> deleteDocument(
          {String? collectionId, String? documentId}) =>
      (super.noSuchMethod(
          Invocation.method(#deleteDocument, [],
              {#collectionId: collectionId, #documentId: documentId}),
          returnValue: _i5.Future<dynamic>.value()) as _i5.Future<dynamic>);
  @override
  _i5.Future<_i3.IndexList> listIndexes({String? collectionId}) =>
      (super.noSuchMethod(
          Invocation.method(#listIndexes, [], {#collectionId: collectionId}),
          returnValue: _i5.Future<_i3.IndexList>.value(_FakeIndexList_16(
              this,
              Invocation.method(
                  #listIndexes, [], {#collectionId: collectionId})))) as _i5
          .Future<_i3.IndexList>);
  @override
  _i5.Future<_i3.Index> createIndex(
          {String? collectionId,
          String? key,
          String? type,
          List<dynamic>? attributes,
          List<dynamic>? orders}) =>
      (super.noSuchMethod(
          Invocation.method(#createIndex, [], {
            #collectionId: collectionId,
            #key: key,
            #type: type,
            #attributes: attributes,
            #orders: orders
          }),
          returnValue: _i5.Future<_i3.Index>.value(_FakeIndex_17(
              this,
              Invocation.method(#createIndex, [], {
                #collectionId: collectionId,
                #key: key,
                #type: type,
                #attributes: attributes,
                #orders: orders
              })))) as _i5.Future<_i3.Index>);
  @override
  _i5.Future<_i3.Index> getIndex({String? collectionId, String? key}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getIndex, [], {#collectionId: collectionId, #key: key}),
              returnValue: _i5.Future<_i3.Index>.value(_FakeIndex_17(
                  this,
                  Invocation.method(
                      #getIndex, [], {#collectionId: collectionId, #key: key}))))
          as _i5.Future<_i3.Index>);
  @override
  _i5.Future<dynamic> deleteIndex({String? collectionId, String? key}) =>
      (super.noSuchMethod(
          Invocation.method(
              #deleteIndex, [], {#collectionId: collectionId, #key: key}),
          returnValue: _i5.Future<dynamic>.value()) as _i5.Future<dynamic>);
}
